name: Build IPQ807x NSS WiFi for 301w

on: workflow_dispatch

jobs:
    build:
        name: Prepare and build IPQ807x NSS images for 301w
        runs-on: self-hosted

        steps:
        
            - name: Checkout
              uses: actions/checkout@v4

            - name: Clone AgustinLorenzo openwrt for IPQ807x
              run: |
                git clone https://github.com/AgustinLorenzo/openwrt.git .

            - name: Clone Argon theme
              run: |
                git clone https://github.com/jerrykuku/luci-theme-argon.git package/luci-theme-argon

            - name: Import full config for IPQ807x NSS
              run: |
                mv custom_feeds.conf.default feeds.conf.default

            - name: Update and install feeds
              run: |
                ./scripts/feeds update -a
                ./scripts/feeds install -a

            - name: Import full config for IPQ807x NSS
              run: |
                mv .full_config_301w .config

            - name: QoL fixes on default config
              run: |
                mkdir -p files/etc/uci-defaults
                cat > files/etc/uci-defaults/99-qol_fixes << EOF
                uci set wireless.radio0.country='US'
                uci set wireless.radio1.country='US'
                uci set wireless.radio2.country='US'
                uci set wireless.radio1.disabled=0
                uci set wireless.radio2.disabled=0
                uci set pbuf.opt.memory_profile=auto
                uci set network.globals.packet_steering=0
                uci set firewall.@defaults[0].flow_offloading=0
                uci set ecm.@general[0].enable_bridge_filtering=0
                uci set system.@system[0].cronloglevel='7'
                /etc/init.d/mwan3 stop
                /etc/init.d/mwan3 disable
                /etc/init.d/sqm stop
                /etc/init.d/sqm disable
                uci commit
                EOF

            - name: Download package sources
              run: make download V=s

            - name: Build tools
              run: |
                make tools/install -j$(nproc) V=s || \
                make tools/install V=s

            - name: Build toolchain
              run: |
                make toolchain/install -j$(nproc) V=s || \
                make toolchain/install V=s

            - name: Build target images
              run: |
                make -j$(nproc) V=s || \
                make V=s

            - name: Get the current date
              run: echo "NOW=$(date +%F-%H%M)" >> $GITHUB_ENV

            - name: Create a release
              uses: "ncipollo/release-action@v1"
              with:
                name: "${{ env.NOW }} | Updated custom prebuilt images for devices (NSS-WiFi)"
                commit: "custom_main_nss"
                tag: "ipq807x-nsswifi-${{ env.NOW }}"
                generateReleaseNotes: true
                makeLatest: true
                artifacts: bin/targets/qualcommax/ipq807x/*
                token: "${{ secrets.GITHUB_TOKEN }}"
